NDefines.NGame.START_DATE = "1985.1.1.12"
NDefines.NGame.END_DATE = "1990.1.1.12"
NDefines.NCountry.EVENT_PROCESS_OFFSET = 1
NDefines.NDiplomacy.VOLUNTEERS_DIVISIONS_REQUIRED = 4
NDefines.NDiplomacy.VOLUNTEERS_PER_TARGET_PROVINCE = 0.325
NDefines.NDiplomacy.VOLUNTEERS_PER_COUNTRY_ARMY = 0.325
NDefines.NDiplomacy.VOLUNTEERS_TRANSFER_SPEED = 5
NDefines_Graphics.NGraphics.TOOLTIP_DELAYED_DELAY = 0.5